name = "a0b_atsam3x8e_twi_i2c"
description = "A0B ATSAM3X8E TWI I2C Driver"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded", "i2c", "atsam3x8e", "twi", "arduino", "due"]

project-files = ["gnat/a0b_atsam3x8e_twi_i2c.gpr"]

[configuration]
disabled = true

[[depends-on]]
a0b_i2c = "*"
a0b_atsam3x8e_gpio = "*"
